name: photo_booth
description: PhotoBooth for Paul&#x27;s Birthday

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  cloud_firestore:
  shared_preferences:
  firebase_auth:
  firebase_storage:
  image_picker:
  intl:
  path_provider:
  image:
  simple_permissions:
  share:
    git:
      url: https://github.com/d-silveira/flutter-share.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - assets/PhotoBoothLogo.png